apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: book.local
      http:
        paths:
          - path: /books(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: book-service
                port:
                  number: 3000

